# set postgresql values for postgresql dependency charts.
# we set postgres username, password, and database name.
# make sure to apply the following values in caaas config values.
postgresql:
  enabled: true
  # PostgreSQL User to create
  postgresqlUsername: caaas-user
  # PostgreSQL Password for the new user
  postgresqlPassword: caaas-password
  # PostgreSQL Database to create
  postgresqlDatabase: caaas-db

# set caaas configs.
caaas:
  # image repository is published over github-container-registery
  image:
    repository: ghcr.io/amirhnajafiz/caaas
    pullPolicy: IfNotPresent
    tag: "v0.1.0"
  
  # setting labels
  labels:
    app: caaas
  
  # if this parameter is set true, database configs will be read from
  # values file of a postgres cluster created by it charts.
  # if set to false, it will read database configs from configs sections in caaas.
  dbConfigsFromPostgresCharts: true

  # replicas only will apply to gateway apps.
  replicas: 5

  # change service type based on your desire, it will be set for both api and gateway.
  # in order to expose gateways, create an ingress or an external service.
  service:
    type: ClusterIP
    port: 80

  # resources will be applied to gateway and api applications
  resources:
    api:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    gateway:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
  # setup config files for api, migrate, and service containers
  configs:
    # giving postgres storage params
    storage:
      host: ""
      port: 5432
      user: "user"
      pass: "password"
      database: "caaas-db"
      ssl: false
    http_server_port: 8080 # default value is 8080
    # prometheus metrics can be exported as a separate server.
    # only works for gateway apps.
    metrics:
      enable: true # if set to disable, no metrics will export
      port: 8081 # if enabled, it will be the exporter's port
    # keys and settings for gateway JWTs.
    auth:
      private_key: "private"
      encryption_salt: "salt"
      tokens_expire_time: 30 # in minutes, default is 30
    logger:
      level: "error" # an enum of (debug, info, warn, error, fatal, panic) default is error
